services:
  sqli-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqli-engine
    environment:
      DISPLAY: ${DISPLAY}
      QT_QPA_PLATFORM: xcb
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - sqli-db:/app/db
      - sqli-exports:/app/exports

volumes:
  sqli-db:
  sqli-exports:
